### PR TITLE
Fix for vulnerable dependency path

### PR DESCRIPTION
**Pull request by benmag1**
webpagetest-charts-api currently has a 3 vulnerable dependency paths, introducing 3 different types of known vulnerabilities.

This PR fixes  vulnerable dependency, [ReDOS vulnerability](https://snyk.io/vuln/npm:tough-cookie:20160722) in the `tough-cookie` dependency.
You can see [Snyk test report](https://snyk.io/test/github/trulia/webpagetest-charts-api) of this project for details. 

This PR changes `Package.json` to upgrade `request` to the newer 2.74.0 version, and will fix all the vulnerabilities listed above.

You can get alerts and fix PRs for future vulnerabilities for free by [watching this repo with Snyk](https://snyk.io/add).

Note this PR fixes all the vulnerabilities introduced trough `request` dependency, in order to be vulnerability free you will need to upgrade others dependencies as well.

Full disclosure: I'm a part of the Snyk team, just looking to spread some security goodness and awareness ;)

### CODE REVIEW

**Comment by alexindigo** [comment]
Thank you.

**Comment by alexindigo** [comment]
@benmag1 Is there a public page I can see with report on this repo?

**Comment by benmag1** [comment]
@alexindigo Yes https://snyk.io/test/github/trulia/webpagetest-charts-api here you can see the report on this repo, and here you can see for all your repos https://snyk.io/add

**Comment by alexindigo** [comment]
Thank you.

**Pull request merged**
